<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dub\Models\Errors;


/** Conflict - This response is sent when a request conflicts with the current state of the server. */
class Conflict
{
    /**
     *
     * @var ConflictError $error
     */
    #[\JMS\Serializer\Annotation\SerializedName('error')]
    #[\JMS\Serializer\Annotation\Type('\Dub\Models\Errors\ConflictError')]
    public ConflictError $error;

    /**
     * @param  ?ConflictError  $error
     */
    public function __construct(?ConflictError $error = null)
    {
        $this->error = $error;
    }
}