<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * Generated under the AGPL-3.0-only license.
 * SPDX-License-Identifier: AGPL-3.0-only
 */

declare(strict_types=1);

namespace Dub\Models\Errors;

class ForbiddenThrowable extends \RuntimeException
{
    public Forbidden $container;

    public function __construct(string $message, int $statusCode, Forbidden $container)
    {
        parent::__construct($message, $statusCode);
        $this->container = $container;
    }
}