<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * Generated under the AGPL-3.0-only license.
 * SPDX-License-Identifier: AGPL-3.0-only
 */


declare(strict_types=1);

namespace Dub\Hooks;

class AfterSuccessContext extends HookContext
{
    public function __construct(HookContext $hookCtx)
    {
        parent::__construct($hookCtx->config, $hookCtx->baseURL, $hookCtx->operationID, $hookCtx->oauth2Scopes, $hookCtx->securitySource);
    }
}
