<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dub\Models\Operations;


class ApproveBountySubmissionFiles
{
    /**
     * The URL of the uploaded file.
     *
     * @var string $url
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('url')]
    public string $url;

    /**
     * The original file name.
     *
     * @var string $fileName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('fileName')]
    public string $fileName;

    /**
     * The file size in bytes.
     *
     * @var float $size
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('size')]
    public float $size;

    /**
     * @param  string  $url
     * @param  string  $fileName
     * @param  float  $size
     * @phpstan-pure
     */
    public function __construct(string $url, string $fileName, float $size)
    {
        $this->url = $url;
        $this->fileName = $fileName;
        $this->size = $size;
    }
}