<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dub\Models\Operations;


class BanPartnerRequestBody
{
    /**
     *
     * @var Reason $reason
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('reason')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dub\Models\Operations\Reason')]
    public Reason $reason;

    /**
     * The ID of the partner to create a link for. Will take precedence over `tenantId` if provided.
     *
     * @var ?string $partnerId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('partnerId')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $partnerId = null;

    /**
     * The ID of the partner in your system. If both `partnerId` and `tenantId` are not provided, an error will be thrown.
     *
     * @var ?string $tenantId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('tenantId')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $tenantId = null;

    /**
     * @param  Reason  $reason
     * @param  ?string  $partnerId
     * @param  ?string  $tenantId
     * @phpstan-pure
     */
    public function __construct(Reason $reason, ?string $partnerId = null, ?string $tenantId = null)
    {
        $this->reason = $reason;
        $this->partnerId = $partnerId;
        $this->tenantId = $tenantId;
    }
}