<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dub\Models\Operations;


class CheckDomainStatusResponseBody
{
    /**
     * The domain name.
     *
     * @var string $domain
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('domain')]
    public string $domain;

    /**
     * Whether the domain is available.
     *
     * @var bool $available
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('available')]
    public bool $available;

    /**
     * Whether the domain is a premium domain.
     *
     * @var ?bool $premium
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('premium')]
    public ?bool $premium;

    /**
     * Price details for the domain. Will be null if the domain is not available.
     *
     * @var ?\Dub\Models\Operations\Prices $prices
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('prices')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dub\Models\Operations\Prices|null')]
    public ?Prices $prices;

    /**
     * Deprecated: Use `prices` instead.
     *
     * @var ?string $price
     * @deprecated  field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('price')]
    public ?string $price;

    /**
     * @param  string  $domain
     * @param  bool  $available
     * @param  ?bool  $premium
     * @param  ?\Dub\Models\Operations\Prices  $prices
     * @param  ?string  $price
     * @phpstan-pure
     */
    public function __construct(string $domain, bool $available, ?bool $premium = null, ?Prices $prices = null, ?string $price = null)
    {
        $this->domain = $domain;
        $this->available = $available;
        $this->premium = $premium;
        $this->prices = $prices;
        $this->price = $price;
    }
}