<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dub\Models\Operations;


class CreateDomainRequestBody
{
    /**
     * Name of the domain.
     *
     * @var string $slug
     */
    #[\JMS\Serializer\Annotation\SerializedName('slug')]
    public string $slug;

    /**
     * Redirect users to a specific URL when any link under this domain has expired.
     *
     * @var ?string $expiredUrl
     */
    #[\JMS\Serializer\Annotation\SerializedName('expiredUrl')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $expiredUrl = null;

    /**
     * Whether to archive this domain. `false` will unarchive a previously archived domain.
     *
     * @var ?bool $archived
     */
    #[\JMS\Serializer\Annotation\SerializedName('archived')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?bool $archived = null;

    /**
     * Provide context to your teammates in the link creation modal by showing them an example of a link to be shortened.
     *
     * @var ?string $placeholder
     */
    #[\JMS\Serializer\Annotation\SerializedName('placeholder')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $placeholder = null;

    /**
     * @param  string  $slug
     * @param  ?bool  $archived
     * @param  ?string  $expiredUrl
     * @param  ?string  $placeholder
     */
    public function __construct(string $slug, ?bool $archived = null, ?string $expiredUrl = null, ?string $placeholder = null)
    {
        $this->slug = $slug;
        $this->archived = $archived;
        $this->expiredUrl = $expiredUrl;
        $this->placeholder = $placeholder;
    }
}