<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dub\Models\Operations;


/** CreatePartnerApplication - Linked program application, including review outcome when applicable. */
class CreatePartnerApplication
{
    /**
     * Preset reason when the application was rejected.
     *
     * @var ?\Dub\Models\Operations\CreatePartnerRejectionReason $rejectionReason
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('rejectionReason')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dub\Models\Operations\CreatePartnerRejectionReason|null')]
    public ?CreatePartnerRejectionReason $rejectionReason;

    /**
     * Free-form note when the application was rejected.
     *
     * @var ?string $rejectionNote
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('rejectionNote')]
    public ?string $rejectionNote;

    /**
     * When the application was approved or rejected.
     *
     * @var ?string $reviewedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('reviewedAt')]
    public ?string $reviewedAt;

    /**
     * @param  ?\Dub\Models\Operations\CreatePartnerRejectionReason  $rejectionReason
     * @param  ?string  $rejectionNote
     * @param  ?string  $reviewedAt
     * @phpstan-pure
     */
    public function __construct(?CreatePartnerRejectionReason $rejectionReason = null, ?string $rejectionNote = null, ?string $reviewedAt = null)
    {
        $this->rejectionReason = $rejectionReason;
        $this->rejectionNote = $rejectionNote;
        $this->reviewedAt = $reviewedAt;
    }
}