<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dub\Models\Operations;


enum GetCustomersInterval: string
{
    case Month = 'month';
    case Year = 'year';
}
