<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dub\Models\Operations;

use Dub\Utils\SpeakeasyMetadata;
class GetLinksRequest
{
    /**
     * The domain to filter the links by. E.g. `ac.me`. If not provided, all links for the workspace will be returned.
     *
     * @var ?string $domain
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=domain')]
    public ?string $domain = null;

    /**
     * Deprecated: Use `tagIds` instead. The tag ID to filter the links by.
     *
     * @var ?string $tagId
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=tagId')]
    public ?string $tagId = null;

    /**
     * The tag IDs to filter the links by.
     *
     * @var string|array<string>|null $tagIds
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=false,name=tagIds')]
    public string|array|null $tagIds = null;

    /**
     * The unique name of the tags assigned to the short link (case insensitive).
     *
     * @var string|array<string>|null $tagNames
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=false,name=tagNames')]
    public string|array|null $tagNames = null;

    /**
     * The folder ID to filter the links by.
     *
     * @var ?string $folderId
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=folderId')]
    public ?string $folderId = null;

    /**
     * The search term to filter the links by. The search term will be matched against the short link slug and the destination url.
     *
     * @var ?string $search
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=search')]
    public ?string $search = null;

    /**
     * The user ID to filter the links by.
     *
     * @var ?string $userId
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=userId')]
    public ?string $userId = null;

    /**
     * The ID of the tenant that created the link inside your system. If set, will only return links for the specified tenant.
     *
     * @var ?string $tenantId
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=tenantId')]
    public ?string $tenantId = null;

    /**
     * If specified, the query only searches for results before this cursor. Mutually exclusive with `startingAfter`.
     *
     * @var ?string $endingBefore
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=endingBefore')]
    public ?string $endingBefore = null;

    /**
     * If specified, the query only searches for results after this cursor. Mutually exclusive with `endingBefore`.
     *
     * @var ?string $startingAfter
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=startingAfter')]
    public ?string $startingAfter = null;

    /**
     * DEPRECATED. Use `startingAfter` instead.
     *
     * @var ?int $page
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=page')]
    public ?int $page = null;

    /**
     * Whether to include archived links in the response. Defaults to `false` if not provided.
     *
     * @var ?bool $showArchived
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=showArchived')]
    public ?bool $showArchived = null;

    /**
     * DEPRECATED. Filter for links that have at least one tag assigned to them.
     *
     * @var ?bool $withTags
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=withTags')]
    public ?bool $withTags = null;

    /**
     * The number of items per page.
     *
     * @var ?int $pageSize
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=pageSize')]
    public ?int $pageSize = null;

    /**
     * @param  ?string  $domain
     * @param  ?string  $tagId
     * @param  string|array<string>|null  $tagIds
     * @param  string|array<string>|null  $tagNames
     * @param  ?string  $folderId
     * @param  ?string  $search
     * @param  ?string  $userId
     * @param  ?string  $tenantId
     * @param  ?bool  $showArchived
     * @param  ?bool  $withTags
     * @param  ?string  $endingBefore
     * @param  ?string  $startingAfter
     * @param  ?int  $page
     * @param  ?int  $pageSize
     * @phpstan-pure
     */
    public function __construct(?string $domain = null, ?string $tagId = null, string|array|null $tagIds = null, string|array|null $tagNames = null, ?string $folderId = null, ?string $search = null, ?string $userId = null, ?string $tenantId = null, ?string $endingBefore = null, ?string $startingAfter = null, ?int $page = null, ?bool $showArchived = false, ?bool $withTags = false, ?int $pageSize = 100)
    {
        $this->domain = $domain;
        $this->tagId = $tagId;
        $this->tagIds = $tagIds;
        $this->tagNames = $tagNames;
        $this->folderId = $folderId;
        $this->search = $search;
        $this->userId = $userId;
        $this->tenantId = $tenantId;
        $this->endingBefore = $endingBefore;
        $this->startingAfter = $startingAfter;
        $this->page = $page;
        $this->showArchived = $showArchived;
        $this->withTags = $withTags;
        $this->pageSize = $pageSize;
    }
}