<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dub\Models\Operations;


/** InvoiceSettings - The partner's invoice settings. */
class InvoiceSettings
{
    /**
     *
     * @var ?string $address
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('address')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $address = null;

    /**
     *
     * @var ?string $taxId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('taxId')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $taxId = null;

    /**
     * @param  ?string  $address
     * @param  ?string  $taxId
     * @phpstan-pure
     */
    public function __construct(?string $address = null, ?string $taxId = null)
    {
        $this->address = $address;
        $this->taxId = $taxId;
    }
}