<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dub\Models\Operations;


/** The field to sort the list of commissions by. */
enum ListCommissionsQueryParamSortBy: string
{
    case CreatedAt = 'createdAt';
    case Amount = 'amount';
}
