<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * Generated under the AGPL-3.0-only license.
 * SPDX-License-Identifier: AGPL-3.0-only
 */

declare(strict_types=1);

namespace Dub\Models\Operations;


/** The sort order. The default is `desc`. */
enum ListPartnersQueryParamSortOrder: string
{
    case Asc = 'asc';
    case Desc = 'desc';
}
