<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dub\Models\Operations;


/** A filter on the list based on the partner's `status` field. */
enum ListPartnersQueryParamStatus: string
{
    case Pending = 'pending';
    case Approved = 'approved';
    case Rejected = 'rejected';
    case Invited = 'invited';
    case Declined = 'declined';
    case Deactivated = 'deactivated';
    case Banned = 'banned';
    case Archived = 'archived';
}
