<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dub\Models\Operations;


/** Prices - Price details for the domain. Will be null if the domain is not available. */
class Prices
{
    /**
     * The domain's registration price in USD cents.
     *
     * @var ?float $registration
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('registration')]
    public ?float $registration;

    /**
     * The domain's renewal price in USD cents.
     *
     * @var ?float $renewal
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('renewal')]
    public ?float $renewal;

    /**
     * @param  ?float  $registration
     * @param  ?float  $renewal
     * @phpstan-pure
     */
    public function __construct(?float $registration = null, ?float $renewal = null)
    {
        $this->registration = $registration;
        $this->renewal = $renewal;
    }
}