<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dub\Models\Operations;


/** The sort order. The default is `desc`. */
enum QueryParamSortOrder: string
{
    case Asc = 'asc';
    case Desc = 'desc';
}
