<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * Generated under the AGPL-3.0-only license.
 * SPDX-License-Identifier: AGPL-3.0-only
 */

declare(strict_types=1);

namespace Dub\Models\Operations;


/** The reason for banning the partner. */
enum Reason: string
{
    case TosViolation = 'tos_violation';
    case InappropriateContent = 'inappropriate_content';
    case FakeTraffic = 'fake_traffic';
    case Fraud = 'fraud';
    case Spam = 'spam';
    case BrandAbuse = 'brand_abuse';
}
