<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dub\Models\Operations;


/** RejectPartnerApplicationResponseBody - The rejected partner */
class RejectPartnerApplicationResponseBody
{
    /**
     * The ID of the rejected partner.
     *
     * @var string $partnerId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('partnerId')]
    public string $partnerId;

    /**
     * @param  string  $partnerId
     * @phpstan-pure
     */
    public function __construct(string $partnerId)
    {
        $this->partnerId = $partnerId;
    }
}