<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dub\Models\Operations;


/**
 * DEPRECATED. Use `sortBy` instead.
 *
 * @deprecated  enum: This will be removed in a future release, please migrate away from it as soon as possible.
 */
enum Sort: string
{
    case CreatedAt = 'createdAt';
    case Clicks = 'clicks';
    case SaleAmount = 'saleAmount';
    case LastClicked = 'lastClicked';
}
