<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dub\Models\Operations;

use Dub\Utils\SpeakeasyMetadata;
class UpdateFolderRequest
{
    /**
     * The ID of the folder to update.
     *
     * @var string $id
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=id')]
    public string $id;

    /**
     *
     * @var ?UpdateFolderRequestBody $requestBody
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public ?UpdateFolderRequestBody $requestBody = null;

    /**
     * @param  string  $id
     * @param  ?UpdateFolderRequestBody  $requestBody
     * @phpstan-pure
     */
    public function __construct(string $id, ?UpdateFolderRequestBody $requestBody = null)
    {
        $this->id = $id;
        $this->requestBody = $requestBody;
    }
}