<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dub\Models\Operations;


/** The type of redirect to use for this domain. */
enum UpdateDomainType: string
{
    case Redirect = 'redirect';
    case Rewrite = 'rewrite';
}
