<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dub\Models\Operations;


/** UpdateCommissionResponseBody - The updated commission. */
class UpdateCommissionResponseBody
{
    /**
     * The commission's unique ID on Dub.
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     *
     * @var float $amount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('amount')]
    public float $amount;

    /**
     *
     * @var float $earnings
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('earnings')]
    public float $earnings;

    /**
     *
     * @var string $currency
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('currency')]
    public string $currency;

    /**
     *
     * @var UpdateCommissionStatus $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dub\Models\Operations\UpdateCommissionStatus')]
    public UpdateCommissionStatus $status;

    /**
     *
     * @var string $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('createdAt')]
    public string $createdAt;

    /**
     *
     * @var string $updatedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('updatedAt')]
    public string $updatedAt;

    /**
     *
     * @var ?UpdateCommissionType $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dub\Models\Operations\UpdateCommissionType|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?UpdateCommissionType $type = null;

    /**
     *
     * @var ?string $invoiceId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('invoiceId')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $invoiceId = null;

    /**
     * @param  string  $id
     * @param  float  $amount
     * @param  float  $earnings
     * @param  string  $currency
     * @param  UpdateCommissionStatus  $status
     * @param  string  $createdAt
     * @param  string  $updatedAt
     * @param  ?UpdateCommissionType  $type
     * @param  ?string  $invoiceId
     * @phpstan-pure
     */
    public function __construct(string $id, float $amount, float $earnings, string $currency, UpdateCommissionStatus $status, string $createdAt, string $updatedAt, ?UpdateCommissionType $type = null, ?string $invoiceId = null)
    {
        $this->id = $id;
        $this->amount = $amount;
        $this->earnings = $earnings;
        $this->currency = $currency;
        $this->status = $status;
        $this->createdAt = $createdAt;
        $this->updatedAt = $updatedAt;
        $this->type = $type;
        $this->invoiceId = $invoiceId;
    }
}