<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dub\Models\Operations;

use Dub\Utils\SpeakeasyMetadata;
class UpdateTagRequest
{
    /**
     * The ID of the tag to update.
     *
     * @var string $id
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=id')]
    public string $id;

    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public ?UpdateTagRequestBody $requestBody = null;

    public function __construct()
    {
        $this->id = '';
        $this->requestBody = null;
    }
}