<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dub\Models\Components;


class AnalyticsTopUrls
{
    /**
     * The destination URL
     *
     * @var string $url
     */
    #[\JMS\Serializer\Annotation\SerializedName('url')]
    public string $url;

    /**
     * The number of clicks from this URL
     *
     * @var float $clicks
     */
    #[\JMS\Serializer\Annotation\SerializedName('clicks')]
    public float $clicks;

    /**
     * The number of leads from this URL
     *
     * @var float $leads
     */
    #[\JMS\Serializer\Annotation\SerializedName('leads')]
    public float $leads;

    /**
     * The number of sales from this URL
     *
     * @var float $sales
     */
    #[\JMS\Serializer\Annotation\SerializedName('sales')]
    public float $sales;

    /**
     * The total amount of sales from this URL
     *
     * @var float $saleAmount
     */
    #[\JMS\Serializer\Annotation\SerializedName('saleAmount')]
    public float $saleAmount;

    /**
     * @param  ?string  $url
     * @param  ?float  $clicks
     * @param  ?float  $leads
     * @param  ?float  $sales
     * @param  ?float  $saleAmount
     */
    public function __construct(?string $url = null, ?float $clicks = null, ?float $leads = null, ?float $sales = null, ?float $saleAmount = null)
    {
        $this->url = $url;
        $this->clicks = $clicks;
        $this->leads = $leads;
        $this->sales = $sales;
        $this->saleAmount = $saleAmount;
    }
}