<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dub\Models\Components;


class ClicksCities
{
    /**
     * The name of the city
     *
     * @var string $city
     */
    #[\JMS\Serializer\Annotation\SerializedName('city')]
    public string $city;

    /**
     * The 2-letter country code of the city: https://d.to/geo
     *
     * @var ClicksCitiesCountry $country
     */
    #[\JMS\Serializer\Annotation\SerializedName('country')]
    #[\JMS\Serializer\Annotation\Type('\Dub\Models\Components\ClicksCitiesCountry')]
    public ClicksCitiesCountry $country;

    /**
     * The number of clicks from this city
     *
     * @var float $clicks
     */
    #[\JMS\Serializer\Annotation\SerializedName('clicks')]
    public float $clicks;

    /**
     * @param  ?string  $city
     * @param  ?ClicksCitiesCountry  $country
     * @param  ?float  $clicks
     */
    public function __construct(?string $city = null, ?ClicksCitiesCountry $country = null, ?float $clicks = null)
    {
        $this->city = $city;
        $this->country = $country;
        $this->clicks = $clicks;
    }
}