<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dub\Models\Components;


/** The 2-letter ISO 3166-1 code representing the continent associated with the location of the user. */
enum Continent: string
{
    case Af = 'AF';
    case An = 'AN';
    case As = 'AS';
    case Eu = 'EU';
    case Na = 'NA';
    case Oc = 'OC';
    case Sa = 'SA';
}
