<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * Generated under the AGPL-3.0-only license.
 * SPDX-License-Identifier: AGPL-3.0-only
 */

declare(strict_types=1);

namespace Dub\Models\Components;


class Discount
{
    /**
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     *
     * @var float $amount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('amount')]
    public float $amount;

    /**
     *
     * @var \Dub\Models\Components\DiscountCodeWebhookEventType $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dub\Models\Components\DiscountCodeWebhookEventType')]
    public DiscountCodeWebhookEventType $type;

    /**
     *
     * @var \Dub\Models\Components\Provider $provider
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('provider')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dub\Models\Components\Provider')]
    public Provider $provider;

    /**
     *
     * @var ?float $maxDuration
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('maxDuration')]
    public ?float $maxDuration;

    /**
     * @param  string  $id
     * @param  float  $amount
     * @param  \Dub\Models\Components\DiscountCodeWebhookEventType  $type
     * @param  \Dub\Models\Components\Provider  $provider
     * @param  ?float  $maxDuration
     * @phpstan-pure
     */
    public function __construct(string $id, float $amount, DiscountCodeWebhookEventType $type, Provider $provider, ?float $maxDuration = null)
    {
        $this->id = $id;
        $this->amount = $amount;
        $this->type = $type;
        $this->provider = $provider;
        $this->maxDuration = $maxDuration;
    }
}