<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dub\Models\Components;


class Domains
{
    /**
     * The domain name.
     * 
     * @var string $slug
     */
	#[\JMS\Serializer\Annotation\SerializedName('slug')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $slug;
    
    /**
     * Whether the domain is the primary domain for the workspace.
     * 
     * @var bool $primary
     */
	#[\JMS\Serializer\Annotation\SerializedName('primary')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    public bool $primary;
    
	public function __construct()
	{
		$this->slug = "";
		$this->primary = false;
	}
}
