<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dub\Models\Components;


class Fields2
{
    /**
     *
     * @var string $key
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('key')]
    public string $key;

    /**
     *
     * @var string $label
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('label')]
    public string $label;

    /**
     *
     * @var bool $required
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('required')]
    public bool $required;

    /**
     *
     * @var bool $locked
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('locked')]
    public bool $locked;

    /**
     *
     * @var int $position
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('position')]
    public int $position;

    /**
     *
     * @var PartnerEnrolledEventFieldsType $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dub\Models\Components\PartnerEnrolledEventFieldsType')]
    public PartnerEnrolledEventFieldsType $type;

    /**
     *
     * @var ?FieldsConstraints $constraints
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('constraints')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dub\Models\Components\FieldsConstraints|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?FieldsConstraints $constraints = null;

    /**
     * @param  string  $key
     * @param  string  $label
     * @param  bool  $required
     * @param  bool  $locked
     * @param  int  $position
     * @param  PartnerEnrolledEventFieldsType  $type
     * @param  ?FieldsConstraints  $constraints
     * @phpstan-pure
     */
    public function __construct(string $key, string $label, bool $required, bool $locked, int $position, PartnerEnrolledEventFieldsType $type, ?FieldsConstraints $constraints = null)
    {
        $this->key = $key;
        $this->label = $label;
        $this->required = $required;
        $this->locked = $locked;
        $this->position = $position;
        $this->type = $type;
        $this->constraints = $constraints;
    }
}