<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dub\Models\Components;


/** Geo - Geo targeting information for the short link in JSON format `{[COUNTRY]: https://example.com }`. Learn more: https://d.to/geo */
class Geo
{
    #[\JMS\Serializer\Annotation\SerializedName('AF')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $af = null;

    #[\JMS\Serializer\Annotation\SerializedName('AL')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $al = null;

    #[\JMS\Serializer\Annotation\SerializedName('DZ')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $dz = null;

    #[\JMS\Serializer\Annotation\SerializedName('AS')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $as = null;

    #[\JMS\Serializer\Annotation\SerializedName('AD')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $ad = null;

    #[\JMS\Serializer\Annotation\SerializedName('AO')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $ao = null;

    #[\JMS\Serializer\Annotation\SerializedName('AI')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $ai = null;

    #[\JMS\Serializer\Annotation\SerializedName('AQ')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $aq = null;

    #[\JMS\Serializer\Annotation\SerializedName('AG')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $ag = null;

    #[\JMS\Serializer\Annotation\SerializedName('AR')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $ar = null;

    #[\JMS\Serializer\Annotation\SerializedName('AM')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $am = null;

    #[\JMS\Serializer\Annotation\SerializedName('AW')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $aw = null;

    #[\JMS\Serializer\Annotation\SerializedName('AU')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $au = null;

    #[\JMS\Serializer\Annotation\SerializedName('AT')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $at = null;

    #[\JMS\Serializer\Annotation\SerializedName('AZ')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $az = null;

    #[\JMS\Serializer\Annotation\SerializedName('BS')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $bs = null;

    #[\JMS\Serializer\Annotation\SerializedName('BH')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $bh = null;

    #[\JMS\Serializer\Annotation\SerializedName('BD')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $bd = null;

    #[\JMS\Serializer\Annotation\SerializedName('BB')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $bb = null;

    #[\JMS\Serializer\Annotation\SerializedName('BY')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $by = null;

    #[\JMS\Serializer\Annotation\SerializedName('BE')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $be = null;

    #[\JMS\Serializer\Annotation\SerializedName('BZ')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $bz = null;

    #[\JMS\Serializer\Annotation\SerializedName('BJ')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $bj = null;

    #[\JMS\Serializer\Annotation\SerializedName('BM')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $bm = null;

    #[\JMS\Serializer\Annotation\SerializedName('BT')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $bt = null;

    #[\JMS\Serializer\Annotation\SerializedName('BO')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $bo = null;

    #[\JMS\Serializer\Annotation\SerializedName('BA')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $ba = null;

    #[\JMS\Serializer\Annotation\SerializedName('BW')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $bw = null;

    #[\JMS\Serializer\Annotation\SerializedName('BV')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $bv = null;

    #[\JMS\Serializer\Annotation\SerializedName('BR')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $br = null;

    #[\JMS\Serializer\Annotation\SerializedName('IO')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $io = null;

    #[\JMS\Serializer\Annotation\SerializedName('BN')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $bn = null;

    #[\JMS\Serializer\Annotation\SerializedName('BG')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $bg = null;

    #[\JMS\Serializer\Annotation\SerializedName('BF')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $bf = null;

    #[\JMS\Serializer\Annotation\SerializedName('BI')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $bi = null;

    #[\JMS\Serializer\Annotation\SerializedName('KH')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $kh = null;

    #[\JMS\Serializer\Annotation\SerializedName('CM')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $cm = null;

    #[\JMS\Serializer\Annotation\SerializedName('CA')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $ca = null;

    #[\JMS\Serializer\Annotation\SerializedName('CV')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $cv = null;

    #[\JMS\Serializer\Annotation\SerializedName('KY')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $ky = null;

    #[\JMS\Serializer\Annotation\SerializedName('CF')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $cf = null;

    #[\JMS\Serializer\Annotation\SerializedName('TD')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $td = null;

    #[\JMS\Serializer\Annotation\SerializedName('CL')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $cl = null;

    #[\JMS\Serializer\Annotation\SerializedName('CN')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $cn = null;

    #[\JMS\Serializer\Annotation\SerializedName('CX')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $cx = null;

    #[\JMS\Serializer\Annotation\SerializedName('CC')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $cc = null;

    #[\JMS\Serializer\Annotation\SerializedName('CO')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $co = null;

    #[\JMS\Serializer\Annotation\SerializedName('KM')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $km = null;

    #[\JMS\Serializer\Annotation\SerializedName('CG')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $cg = null;

    #[\JMS\Serializer\Annotation\SerializedName('CD')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $cd = null;

    #[\JMS\Serializer\Annotation\SerializedName('CK')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $ck = null;

    #[\JMS\Serializer\Annotation\SerializedName('CR')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $cr = null;

    #[\JMS\Serializer\Annotation\SerializedName('CI')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $ci = null;

    #[\JMS\Serializer\Annotation\SerializedName('HR')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $hr = null;

    #[\JMS\Serializer\Annotation\SerializedName('CU')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $cu = null;

    #[\JMS\Serializer\Annotation\SerializedName('CY')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $cy = null;

    #[\JMS\Serializer\Annotation\SerializedName('CZ')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $cz = null;

    #[\JMS\Serializer\Annotation\SerializedName('DK')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $dk = null;

    #[\JMS\Serializer\Annotation\SerializedName('DJ')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $dj = null;

    #[\JMS\Serializer\Annotation\SerializedName('DM')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $dm = null;

    #[\JMS\Serializer\Annotation\SerializedName('DO')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $do = null;

    #[\JMS\Serializer\Annotation\SerializedName('EC')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $ec = null;

    #[\JMS\Serializer\Annotation\SerializedName('EG')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $eg = null;

    #[\JMS\Serializer\Annotation\SerializedName('SV')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $sv = null;

    #[\JMS\Serializer\Annotation\SerializedName('GQ')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $gq = null;

    #[\JMS\Serializer\Annotation\SerializedName('ER')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $er = null;

    #[\JMS\Serializer\Annotation\SerializedName('EE')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $ee = null;

    #[\JMS\Serializer\Annotation\SerializedName('ET')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $et = null;

    #[\JMS\Serializer\Annotation\SerializedName('FK')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $fk = null;

    #[\JMS\Serializer\Annotation\SerializedName('FO')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $fo = null;

    #[\JMS\Serializer\Annotation\SerializedName('FJ')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $fj = null;

    #[\JMS\Serializer\Annotation\SerializedName('FI')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $fi = null;

    #[\JMS\Serializer\Annotation\SerializedName('FR')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $fr = null;

    #[\JMS\Serializer\Annotation\SerializedName('GF')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $gf = null;

    #[\JMS\Serializer\Annotation\SerializedName('PF')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $pf = null;

    #[\JMS\Serializer\Annotation\SerializedName('TF')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $tf = null;

    #[\JMS\Serializer\Annotation\SerializedName('GA')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $ga = null;

    #[\JMS\Serializer\Annotation\SerializedName('GM')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $gm = null;

    #[\JMS\Serializer\Annotation\SerializedName('GE')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $ge = null;

    #[\JMS\Serializer\Annotation\SerializedName('DE')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $de = null;

    #[\JMS\Serializer\Annotation\SerializedName('GH')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $gh = null;

    #[\JMS\Serializer\Annotation\SerializedName('GI')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $gi = null;

    #[\JMS\Serializer\Annotation\SerializedName('GR')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $gr = null;

    #[\JMS\Serializer\Annotation\SerializedName('GL')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $gl = null;

    #[\JMS\Serializer\Annotation\SerializedName('GD')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $gd = null;

    #[\JMS\Serializer\Annotation\SerializedName('GP')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $gp = null;

    #[\JMS\Serializer\Annotation\SerializedName('GU')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $gu = null;

    #[\JMS\Serializer\Annotation\SerializedName('GT')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $gt = null;

    #[\JMS\Serializer\Annotation\SerializedName('GN')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $gn = null;

    #[\JMS\Serializer\Annotation\SerializedName('GW')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $gw = null;

    #[\JMS\Serializer\Annotation\SerializedName('GY')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $gy = null;

    #[\JMS\Serializer\Annotation\SerializedName('HT')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $ht = null;

    #[\JMS\Serializer\Annotation\SerializedName('HM')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $hm = null;

    #[\JMS\Serializer\Annotation\SerializedName('VA')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $va = null;

    #[\JMS\Serializer\Annotation\SerializedName('HN')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $hn = null;

    #[\JMS\Serializer\Annotation\SerializedName('HK')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $hk = null;

    #[\JMS\Serializer\Annotation\SerializedName('HU')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $hu = null;

    #[\JMS\Serializer\Annotation\SerializedName('IS')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $is = null;

    #[\JMS\Serializer\Annotation\SerializedName('IN')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $in = null;

    #[\JMS\Serializer\Annotation\SerializedName('ID')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $id = null;

    #[\JMS\Serializer\Annotation\SerializedName('IR')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $ir = null;

    #[\JMS\Serializer\Annotation\SerializedName('IQ')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $iq = null;

    #[\JMS\Serializer\Annotation\SerializedName('IE')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $ie = null;

    #[\JMS\Serializer\Annotation\SerializedName('IL')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $il = null;

    #[\JMS\Serializer\Annotation\SerializedName('IT')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $it = null;

    #[\JMS\Serializer\Annotation\SerializedName('JM')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $jm = null;

    #[\JMS\Serializer\Annotation\SerializedName('JP')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $jp = null;

    #[\JMS\Serializer\Annotation\SerializedName('JO')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $jo = null;

    #[\JMS\Serializer\Annotation\SerializedName('KZ')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $kz = null;

    #[\JMS\Serializer\Annotation\SerializedName('KE')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $ke = null;

    #[\JMS\Serializer\Annotation\SerializedName('KI')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $ki = null;

    #[\JMS\Serializer\Annotation\SerializedName('KP')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $kp = null;

    #[\JMS\Serializer\Annotation\SerializedName('KR')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $kr = null;

    #[\JMS\Serializer\Annotation\SerializedName('KW')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $kw = null;

    #[\JMS\Serializer\Annotation\SerializedName('KG')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $kg = null;

    #[\JMS\Serializer\Annotation\SerializedName('LA')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $la = null;

    #[\JMS\Serializer\Annotation\SerializedName('LV')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $lv = null;

    #[\JMS\Serializer\Annotation\SerializedName('LB')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $lb = null;

    #[\JMS\Serializer\Annotation\SerializedName('LS')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $ls = null;

    #[\JMS\Serializer\Annotation\SerializedName('LR')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $lr = null;

    #[\JMS\Serializer\Annotation\SerializedName('LY')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $ly = null;

    #[\JMS\Serializer\Annotation\SerializedName('LI')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $li = null;

    #[\JMS\Serializer\Annotation\SerializedName('LT')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $lt = null;

    #[\JMS\Serializer\Annotation\SerializedName('LU')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $lu = null;

    #[\JMS\Serializer\Annotation\SerializedName('MO')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $mo = null;

    #[\JMS\Serializer\Annotation\SerializedName('MG')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $mg = null;

    #[\JMS\Serializer\Annotation\SerializedName('MW')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $mw = null;

    #[\JMS\Serializer\Annotation\SerializedName('MY')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $my = null;

    #[\JMS\Serializer\Annotation\SerializedName('MV')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $mv = null;

    #[\JMS\Serializer\Annotation\SerializedName('ML')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $ml = null;

    #[\JMS\Serializer\Annotation\SerializedName('MT')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $mt = null;

    #[\JMS\Serializer\Annotation\SerializedName('MH')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $mh = null;

    #[\JMS\Serializer\Annotation\SerializedName('MQ')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $mq = null;

    #[\JMS\Serializer\Annotation\SerializedName('MR')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $mr = null;

    #[\JMS\Serializer\Annotation\SerializedName('MU')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $mu = null;

    #[\JMS\Serializer\Annotation\SerializedName('YT')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $yt = null;

    #[\JMS\Serializer\Annotation\SerializedName('MX')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $mx = null;

    #[\JMS\Serializer\Annotation\SerializedName('FM')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $fm = null;

    #[\JMS\Serializer\Annotation\SerializedName('MD')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $md = null;

    #[\JMS\Serializer\Annotation\SerializedName('MC')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $mc = null;

    #[\JMS\Serializer\Annotation\SerializedName('MN')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $mn = null;

    #[\JMS\Serializer\Annotation\SerializedName('MS')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $ms = null;

    #[\JMS\Serializer\Annotation\SerializedName('MA')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $ma = null;

    #[\JMS\Serializer\Annotation\SerializedName('MZ')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $mz = null;

    #[\JMS\Serializer\Annotation\SerializedName('MM')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $mm = null;

    #[\JMS\Serializer\Annotation\SerializedName('NA')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $na = null;

    #[\JMS\Serializer\Annotation\SerializedName('NR')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $nr = null;

    #[\JMS\Serializer\Annotation\SerializedName('NP')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $np = null;

    #[\JMS\Serializer\Annotation\SerializedName('NL')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $nl = null;

    #[\JMS\Serializer\Annotation\SerializedName('NC')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $nc = null;

    #[\JMS\Serializer\Annotation\SerializedName('NZ')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $nz = null;

    #[\JMS\Serializer\Annotation\SerializedName('NI')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $ni = null;

    #[\JMS\Serializer\Annotation\SerializedName('NE')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $ne = null;

    #[\JMS\Serializer\Annotation\SerializedName('NG')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $ng = null;

    #[\JMS\Serializer\Annotation\SerializedName('NU')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $nu = null;

    #[\JMS\Serializer\Annotation\SerializedName('NF')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $nf = null;

    #[\JMS\Serializer\Annotation\SerializedName('MK')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $mk = null;

    #[\JMS\Serializer\Annotation\SerializedName('MP')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $mp = null;

    #[\JMS\Serializer\Annotation\SerializedName('NO')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $no = null;

    #[\JMS\Serializer\Annotation\SerializedName('OM')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $om = null;

    #[\JMS\Serializer\Annotation\SerializedName('PK')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $pk = null;

    #[\JMS\Serializer\Annotation\SerializedName('PW')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $pw = null;

    #[\JMS\Serializer\Annotation\SerializedName('PS')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $ps = null;

    #[\JMS\Serializer\Annotation\SerializedName('PA')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $pa = null;

    #[\JMS\Serializer\Annotation\SerializedName('PG')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $pg = null;

    #[\JMS\Serializer\Annotation\SerializedName('PY')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $py = null;

    #[\JMS\Serializer\Annotation\SerializedName('PE')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $pe = null;

    #[\JMS\Serializer\Annotation\SerializedName('PH')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $ph = null;

    #[\JMS\Serializer\Annotation\SerializedName('PN')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $pn = null;

    #[\JMS\Serializer\Annotation\SerializedName('PL')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $pl = null;

    #[\JMS\Serializer\Annotation\SerializedName('PT')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $pt = null;

    #[\JMS\Serializer\Annotation\SerializedName('PR')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $pr = null;

    #[\JMS\Serializer\Annotation\SerializedName('QA')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $qa = null;

    #[\JMS\Serializer\Annotation\SerializedName('RE')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $re = null;

    #[\JMS\Serializer\Annotation\SerializedName('RO')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $ro = null;

    #[\JMS\Serializer\Annotation\SerializedName('RU')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $ru = null;

    #[\JMS\Serializer\Annotation\SerializedName('RW')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $rw = null;

    #[\JMS\Serializer\Annotation\SerializedName('SH')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $sh = null;

    #[\JMS\Serializer\Annotation\SerializedName('KN')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $kn = null;

    #[\JMS\Serializer\Annotation\SerializedName('LC')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $lc = null;

    #[\JMS\Serializer\Annotation\SerializedName('PM')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $pm = null;

    #[\JMS\Serializer\Annotation\SerializedName('VC')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $vc = null;

    #[\JMS\Serializer\Annotation\SerializedName('WS')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $ws = null;

    #[\JMS\Serializer\Annotation\SerializedName('SM')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $sm = null;

    #[\JMS\Serializer\Annotation\SerializedName('ST')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $st = null;

    #[\JMS\Serializer\Annotation\SerializedName('SA')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $sa = null;

    #[\JMS\Serializer\Annotation\SerializedName('SN')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $sn = null;

    #[\JMS\Serializer\Annotation\SerializedName('SC')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $sc = null;

    #[\JMS\Serializer\Annotation\SerializedName('SL')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $sl = null;

    #[\JMS\Serializer\Annotation\SerializedName('SG')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $sg = null;

    #[\JMS\Serializer\Annotation\SerializedName('SK')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $sk = null;

    #[\JMS\Serializer\Annotation\SerializedName('SI')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $si = null;

    #[\JMS\Serializer\Annotation\SerializedName('SB')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $sb = null;

    #[\JMS\Serializer\Annotation\SerializedName('SO')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $so = null;

    #[\JMS\Serializer\Annotation\SerializedName('ZA')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $za = null;

    #[\JMS\Serializer\Annotation\SerializedName('GS')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $gs = null;

    #[\JMS\Serializer\Annotation\SerializedName('ES')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $es = null;

    #[\JMS\Serializer\Annotation\SerializedName('LK')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $lk = null;

    #[\JMS\Serializer\Annotation\SerializedName('SD')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $sd = null;

    #[\JMS\Serializer\Annotation\SerializedName('SR')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $sr = null;

    #[\JMS\Serializer\Annotation\SerializedName('SJ')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $sj = null;

    #[\JMS\Serializer\Annotation\SerializedName('SZ')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $sz = null;

    #[\JMS\Serializer\Annotation\SerializedName('SE')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $se = null;

    #[\JMS\Serializer\Annotation\SerializedName('CH')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $ch = null;

    #[\JMS\Serializer\Annotation\SerializedName('SY')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $sy = null;

    #[\JMS\Serializer\Annotation\SerializedName('TW')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $tw = null;

    #[\JMS\Serializer\Annotation\SerializedName('TJ')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $tj = null;

    #[\JMS\Serializer\Annotation\SerializedName('TZ')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $tz = null;

    #[\JMS\Serializer\Annotation\SerializedName('TH')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $th = null;

    #[\JMS\Serializer\Annotation\SerializedName('TL')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $tl = null;

    #[\JMS\Serializer\Annotation\SerializedName('TG')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $tg = null;

    #[\JMS\Serializer\Annotation\SerializedName('TK')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $tk = null;

    #[\JMS\Serializer\Annotation\SerializedName('TO')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $to = null;

    #[\JMS\Serializer\Annotation\SerializedName('TT')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $tt = null;

    #[\JMS\Serializer\Annotation\SerializedName('TN')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $tn = null;

    #[\JMS\Serializer\Annotation\SerializedName('TR')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $tr = null;

    #[\JMS\Serializer\Annotation\SerializedName('TM')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $tm = null;

    #[\JMS\Serializer\Annotation\SerializedName('TC')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $tc = null;

    #[\JMS\Serializer\Annotation\SerializedName('TV')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $tv = null;

    #[\JMS\Serializer\Annotation\SerializedName('UG')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $ug = null;

    #[\JMS\Serializer\Annotation\SerializedName('UA')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $ua = null;

    #[\JMS\Serializer\Annotation\SerializedName('AE')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $ae = null;

    #[\JMS\Serializer\Annotation\SerializedName('GB')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $gb = null;

    #[\JMS\Serializer\Annotation\SerializedName('US')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $us = null;

    #[\JMS\Serializer\Annotation\SerializedName('UM')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $um = null;

    #[\JMS\Serializer\Annotation\SerializedName('UY')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $uy = null;

    #[\JMS\Serializer\Annotation\SerializedName('UZ')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $uz = null;

    #[\JMS\Serializer\Annotation\SerializedName('VU')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $vu = null;

    #[\JMS\Serializer\Annotation\SerializedName('VE')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $ve = null;

    #[\JMS\Serializer\Annotation\SerializedName('VN')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $vn = null;

    #[\JMS\Serializer\Annotation\SerializedName('VG')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $vg = null;

    #[\JMS\Serializer\Annotation\SerializedName('VI')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $vi = null;

    #[\JMS\Serializer\Annotation\SerializedName('WF')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $wf = null;

    #[\JMS\Serializer\Annotation\SerializedName('EH')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $eh = null;

    #[\JMS\Serializer\Annotation\SerializedName('YE')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $ye = null;

    #[\JMS\Serializer\Annotation\SerializedName('ZM')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $zm = null;

    #[\JMS\Serializer\Annotation\SerializedName('ZW')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $zw = null;

    #[\JMS\Serializer\Annotation\SerializedName('AX')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $ax = null;

    #[\JMS\Serializer\Annotation\SerializedName('BQ')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $bq = null;

    #[\JMS\Serializer\Annotation\SerializedName('CW')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $cw = null;

    #[\JMS\Serializer\Annotation\SerializedName('GG')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $gg = null;

    #[\JMS\Serializer\Annotation\SerializedName('IM')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $im = null;

    #[\JMS\Serializer\Annotation\SerializedName('JE')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $je = null;

    #[\JMS\Serializer\Annotation\SerializedName('ME')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $me = null;

    #[\JMS\Serializer\Annotation\SerializedName('BL')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $bl = null;

    #[\JMS\Serializer\Annotation\SerializedName('MF')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $mf = null;

    #[\JMS\Serializer\Annotation\SerializedName('RS')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $rs = null;

    #[\JMS\Serializer\Annotation\SerializedName('SX')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $sx = null;

    #[\JMS\Serializer\Annotation\SerializedName('SS')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $ss = null;

    #[\JMS\Serializer\Annotation\SerializedName('XK')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $xk = null;

    public function __construct()
    {
        $this->af = null;
        $this->al = null;
        $this->dz = null;
        $this->as = null;
        $this->ad = null;
        $this->ao = null;
        $this->ai = null;
        $this->aq = null;
        $this->ag = null;
        $this->ar = null;
        $this->am = null;
        $this->aw = null;
        $this->au = null;
        $this->at = null;
        $this->az = null;
        $this->bs = null;
        $this->bh = null;
        $this->bd = null;
        $this->bb = null;
        $this->by = null;
        $this->be = null;
        $this->bz = null;
        $this->bj = null;
        $this->bm = null;
        $this->bt = null;
        $this->bo = null;
        $this->ba = null;
        $this->bw = null;
        $this->bv = null;
        $this->br = null;
        $this->io = null;
        $this->bn = null;
        $this->bg = null;
        $this->bf = null;
        $this->bi = null;
        $this->kh = null;
        $this->cm = null;
        $this->ca = null;
        $this->cv = null;
        $this->ky = null;
        $this->cf = null;
        $this->td = null;
        $this->cl = null;
        $this->cn = null;
        $this->cx = null;
        $this->cc = null;
        $this->co = null;
        $this->km = null;
        $this->cg = null;
        $this->cd = null;
        $this->ck = null;
        $this->cr = null;
        $this->ci = null;
        $this->hr = null;
        $this->cu = null;
        $this->cy = null;
        $this->cz = null;
        $this->dk = null;
        $this->dj = null;
        $this->dm = null;
        $this->do = null;
        $this->ec = null;
        $this->eg = null;
        $this->sv = null;
        $this->gq = null;
        $this->er = null;
        $this->ee = null;
        $this->et = null;
        $this->fk = null;
        $this->fo = null;
        $this->fj = null;
        $this->fi = null;
        $this->fr = null;
        $this->gf = null;
        $this->pf = null;
        $this->tf = null;
        $this->ga = null;
        $this->gm = null;
        $this->ge = null;
        $this->de = null;
        $this->gh = null;
        $this->gi = null;
        $this->gr = null;
        $this->gl = null;
        $this->gd = null;
        $this->gp = null;
        $this->gu = null;
        $this->gt = null;
        $this->gn = null;
        $this->gw = null;
        $this->gy = null;
        $this->ht = null;
        $this->hm = null;
        $this->va = null;
        $this->hn = null;
        $this->hk = null;
        $this->hu = null;
        $this->is = null;
        $this->in = null;
        $this->id = null;
        $this->ir = null;
        $this->iq = null;
        $this->ie = null;
        $this->il = null;
        $this->it = null;
        $this->jm = null;
        $this->jp = null;
        $this->jo = null;
        $this->kz = null;
        $this->ke = null;
        $this->ki = null;
        $this->kp = null;
        $this->kr = null;
        $this->kw = null;
        $this->kg = null;
        $this->la = null;
        $this->lv = null;
        $this->lb = null;
        $this->ls = null;
        $this->lr = null;
        $this->ly = null;
        $this->li = null;
        $this->lt = null;
        $this->lu = null;
        $this->mo = null;
        $this->mg = null;
        $this->mw = null;
        $this->my = null;
        $this->mv = null;
        $this->ml = null;
        $this->mt = null;
        $this->mh = null;
        $this->mq = null;
        $this->mr = null;
        $this->mu = null;
        $this->yt = null;
        $this->mx = null;
        $this->fm = null;
        $this->md = null;
        $this->mc = null;
        $this->mn = null;
        $this->ms = null;
        $this->ma = null;
        $this->mz = null;
        $this->mm = null;
        $this->na = null;
        $this->nr = null;
        $this->np = null;
        $this->nl = null;
        $this->nc = null;
        $this->nz = null;
        $this->ni = null;
        $this->ne = null;
        $this->ng = null;
        $this->nu = null;
        $this->nf = null;
        $this->mk = null;
        $this->mp = null;
        $this->no = null;
        $this->om = null;
        $this->pk = null;
        $this->pw = null;
        $this->ps = null;
        $this->pa = null;
        $this->pg = null;
        $this->py = null;
        $this->pe = null;
        $this->ph = null;
        $this->pn = null;
        $this->pl = null;
        $this->pt = null;
        $this->pr = null;
        $this->qa = null;
        $this->re = null;
        $this->ro = null;
        $this->ru = null;
        $this->rw = null;
        $this->sh = null;
        $this->kn = null;
        $this->lc = null;
        $this->pm = null;
        $this->vc = null;
        $this->ws = null;
        $this->sm = null;
        $this->st = null;
        $this->sa = null;
        $this->sn = null;
        $this->sc = null;
        $this->sl = null;
        $this->sg = null;
        $this->sk = null;
        $this->si = null;
        $this->sb = null;
        $this->so = null;
        $this->za = null;
        $this->gs = null;
        $this->es = null;
        $this->lk = null;
        $this->sd = null;
        $this->sr = null;
        $this->sj = null;
        $this->sz = null;
        $this->se = null;
        $this->ch = null;
        $this->sy = null;
        $this->tw = null;
        $this->tj = null;
        $this->tz = null;
        $this->th = null;
        $this->tl = null;
        $this->tg = null;
        $this->tk = null;
        $this->to = null;
        $this->tt = null;
        $this->tn = null;
        $this->tr = null;
        $this->tm = null;
        $this->tc = null;
        $this->tv = null;
        $this->ug = null;
        $this->ua = null;
        $this->ae = null;
        $this->gb = null;
        $this->us = null;
        $this->um = null;
        $this->uy = null;
        $this->uz = null;
        $this->vu = null;
        $this->ve = null;
        $this->vn = null;
        $this->vg = null;
        $this->vi = null;
        $this->wf = null;
        $this->eh = null;
        $this->ye = null;
        $this->zm = null;
        $this->zw = null;
        $this->ax = null;
        $this->bq = null;
        $this->cw = null;
        $this->gg = null;
        $this->im = null;
        $this->je = null;
        $this->me = null;
        $this->bl = null;
        $this->mf = null;
        $this->rs = null;
        $this->sx = null;
        $this->ss = null;
        $this->xk = null;
    }
}