<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dub\Models\Components;


class InviteExpired
{
    #[\JMS\Serializer\Annotation\SerializedName('error')]
    #[\JMS\Serializer\Annotation\Type('Dub\Models\Components\InviteExpiredError')]
    public InviteExpiredError $error;

    public function __construct()
    {
        $this->error = new \Dub\Models\Components\InviteExpiredError();
    }
}