<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dub\Models\Components;


class LeadsTimeseries
{
    /**
     * The starting timestamp of the interval
     *
     * @var string $start
     */
    #[\JMS\Serializer\Annotation\SerializedName('start')]
    public string $start;

    /**
     * The number of leads in the interval
     *
     * @var float $leads
     */
    #[\JMS\Serializer\Annotation\SerializedName('leads')]
    public float $leads;

    /**
     * @param  ?string  $start
     * @param  ?float  $leads
     */
    public function __construct(?string $start = null, ?float $leads = null)
    {
        $this->start = $start;
        $this->leads = $leads;
    }
}