<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dub\Models\Components;


class LeadCreatedEventDiscount
{
    /**
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     *
     * @var float $amount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('amount')]
    public float $amount;

    /**
     *
     * @var LeadCreatedEventType $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dub\Models\Components\LeadCreatedEventType')]
    public LeadCreatedEventType $type;

    /**
     *
     * @var ?string $couponId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('couponId')]
    public ?string $couponId;

    /**
     *
     * @var ?string $couponTestId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('couponTestId')]
    public ?string $couponTestId;

    /**
     *
     * @var ?float $duration
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('duration')]
    public ?float $duration;

    /**
     *
     * @var ?LeadCreatedEventInterval $interval
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('interval')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dub\Models\Components\LeadCreatedEventInterval|null')]
    public ?LeadCreatedEventInterval $interval;

    /**
     * @param  string  $id
     * @param  float  $amount
     * @param  LeadCreatedEventType  $type
     * @param  ?string  $couponId
     * @param  ?string  $couponTestId
     * @param  ?float  $duration
     * @param  ?LeadCreatedEventInterval  $interval
     * @phpstan-pure
     */
    public function __construct(string $id, float $amount, LeadCreatedEventType $type, ?string $couponId = null, ?string $couponTestId = null, ?float $duration = null, ?LeadCreatedEventInterval $interval = null)
    {
        $this->id = $id;
        $this->amount = $amount;
        $this->type = $type;
        $this->couponId = $couponId;
        $this->couponTestId = $couponTestId;
        $this->duration = $duration;
        $this->interval = $interval;
    }
}