<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dub\Models\Components;


/** LinkWebhookEvent - Triggered when a link is created, updated, or deleted. */
class LinkWebhookEvent
{
    /**
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     *
     * @var One|Two|Three $event
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('event')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dub\Models\Components\One|\Dub\Models\Components\Two|\Dub\Models\Components\Three')]
    public One|Two|Three $event;

    /**
     *
     * @var string $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('createdAt')]
    public string $createdAt;

    /**
     *
     * @var LinkWebhookEventLink $data
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dub\Models\Components\LinkWebhookEventLink')]
    public LinkWebhookEventLink $data;

    /**
     * @param  string  $id
     * @param  One|Two|Three  $event
     * @param  string  $createdAt
     * @param  LinkWebhookEventLink  $data
     * @phpstan-pure
     */
    public function __construct(string $id, One|Two|Three $event, string $createdAt, LinkWebhookEventLink $data)
    {
        $this->id = $id;
        $this->event = $event;
        $this->createdAt = $createdAt;
        $this->data = $data;
    }
}