<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dub\Models\Components;


class LinkClickedEventData
{
    /**
     *
     * @var \Dub\Models\Components\Click $click
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('click')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dub\Models\Components\Click')]
    public Click $click;

    /**
     *
     * @var \Dub\Models\Components\Link $link
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('link')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dub\Models\Components\Link')]
    public Link $link;

    /**
     * @param  \Dub\Models\Components\Click  $click
     * @param  \Dub\Models\Components\Link  $link
     * @phpstan-pure
     */
    public function __construct(Click $click, Link $link)
    {
        $this->click = $click;
        $this->link = $link;
    }
}