<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dub\Models\Components;


enum PartnerEnrolledEventFieldsDataReferralFormData7Type: string
{
    case Number = 'number';
}
