<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dub\Models\Components;


/** PartnerCreatedEvent - Triggered when a partner is created. */
class PartnerCreatedEvent
{
    /**
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     *
     * @var PartnerCreatedEventEvent $event
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('event')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dub\Models\Components\PartnerCreatedEventEvent')]
    public PartnerCreatedEventEvent $event;

    /**
     *
     * @var string $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('createdAt')]
    public string $createdAt;

    /**
     *
     * @var PartnerCreatedEventData $data
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dub\Models\Components\PartnerCreatedEventData')]
    public PartnerCreatedEventData $data;

    /**
     * @param  string  $id
     * @param  PartnerCreatedEventEvent  $event
     * @param  string  $createdAt
     * @param  PartnerCreatedEventData  $data
     * @phpstan-pure
     */
    public function __construct(string $id, PartnerCreatedEventEvent $event, string $createdAt, PartnerCreatedEventData $data)
    {
        $this->id = $id;
        $this->event = $event;
        $this->createdAt = $createdAt;
        $this->data = $data;
    }
}