<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dub\Models\Components;


enum ProgramApplicationCreatedEventType: string
{
    case Website = 'website';
    case Youtube = 'youtube';
    case Twitter = 'twitter';
    case Linkedin = 'linkedin';
    case Instagram = 'instagram';
    case Tiktok = 'tiktok';
}
