<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dub\Models\Components;


class ReferralFormData
{
    /**
     * $fields
     *
     * @var array<Fields1|Fields2|Fields3|Four|Five|Six|Seven|Eight> $fields
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('fields')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Dub\Models\Components\Fields1|\Dub\Models\Components\Fields2|\Dub\Models\Components\Fields3|\Dub\Models\Components\Four|\Dub\Models\Components\Five|\Dub\Models\Components\Six|\Dub\Models\Components\Seven|\Dub\Models\Components\Eight>')]
    public array $fields;

    /**
     * @param  array<Fields1|Fields2|Fields3|Four|Five|Six|Seven|Eight>  $fields
     * @phpstan-pure
     */
    public function __construct(array $fields)
    {
        $this->fields = $fields;
    }
}