<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dub\Models\Components;


/** RegisteredDomain - The registered domain record. */
class RegisteredDomain
{
    /**
     * The ID of the registered domain record.
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     * The date the domain was created.
     *
     * @var string $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('createdAt')]
    public string $createdAt;

    /**
     * The date the domain expires.
     *
     * @var string $expiresAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('expiresAt')]
    public string $expiresAt;

    /**
     * @param  string  $id
     * @param  string  $createdAt
     * @param  string  $expiresAt
     */
    public function __construct(string $id, string $createdAt, string $expiresAt)
    {
        $this->id = $id;
        $this->createdAt = $createdAt;
        $this->expiresAt = $expiresAt;
    }
}