<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dub\Models\Components;


class SaleCreatedEventPartner
{
    /**
     * The partner's unique ID on Dub.
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     * The partner's full legal name.
     *
     * @var string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    public string $name;

    /**
     *
     * @var float $totalClicks
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('totalClicks')]
    public float $totalClicks;

    /**
     *
     * @var float $totalLeads
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('totalLeads')]
    public float $totalLeads;

    /**
     *
     * @var float $totalConversions
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('totalConversions')]
    public float $totalConversions;

    /**
     *
     * @var float $totalSales
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('totalSales')]
    public float $totalSales;

    /**
     *
     * @var float $totalSaleAmount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('totalSaleAmount')]
    public float $totalSaleAmount;

    /**
     *
     * @var float $totalCommissions
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('totalCommissions')]
    public float $totalCommissions;

    /**
     * The partner's email address. Should be a unique value across Dub.
     *
     * @var ?string $email
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('email')]
    public ?string $email;

    /**
     * The partner's avatar image.
     *
     * @var ?string $image
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('image')]
    public ?string $image;

    /**
     * The date when the partner enabled payouts.
     *
     * @var ?string $payoutsEnabledAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('payoutsEnabledAt')]
    public ?string $payoutsEnabledAt;

    /**
     * The partner's country (required for tax purposes).
     *
     * @var ?string $country
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('country')]
    public ?string $country;

    /**
     * @param  string  $id
     * @param  string  $name
     * @param  float  $totalClicks
     * @param  float  $totalLeads
     * @param  float  $totalConversions
     * @param  float  $totalSales
     * @param  float  $totalSaleAmount
     * @param  float  $totalCommissions
     * @param  ?string  $email
     * @param  ?string  $image
     * @param  ?string  $payoutsEnabledAt
     * @param  ?string  $country
     * @phpstan-pure
     */
    public function __construct(string $id, string $name, float $totalClicks, float $totalLeads, float $totalConversions, float $totalSales, float $totalSaleAmount, float $totalCommissions, ?string $email = null, ?string $image = null, ?string $payoutsEnabledAt = null, ?string $country = null)
    {
        $this->id = $id;
        $this->name = $name;
        $this->totalClicks = $totalClicks;
        $this->totalLeads = $totalLeads;
        $this->totalConversions = $totalConversions;
        $this->totalSales = $totalSales;
        $this->totalSaleAmount = $totalSaleAmount;
        $this->totalCommissions = $totalCommissions;
        $this->email = $email;
        $this->image = $image;
        $this->payoutsEnabledAt = $payoutsEnabledAt;
        $this->country = $country;
    }
}