<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dub\Models\Components;


class SaleCreatedEventData
{
    /**
     *
     * @var string $eventName
     */
    #[\JMS\Serializer\Annotation\SerializedName('eventName')]
    public string $eventName;

    /**
     *
     * @var SaleCreatedEventCustomer $customer
     */
    #[\JMS\Serializer\Annotation\SerializedName('customer')]
    #[\JMS\Serializer\Annotation\Type('\Dub\Models\Components\SaleCreatedEventCustomer')]
    public SaleCreatedEventCustomer $customer;

    /**
     *
     * @var SaleCreatedEventClick $click
     */
    #[\JMS\Serializer\Annotation\SerializedName('click')]
    #[\JMS\Serializer\Annotation\Type('\Dub\Models\Components\SaleCreatedEventClick')]
    public SaleCreatedEventClick $click;

    /**
     *
     * @var SaleCreatedEventLink $link
     */
    #[\JMS\Serializer\Annotation\SerializedName('link')]
    #[\JMS\Serializer\Annotation\Type('\Dub\Models\Components\SaleCreatedEventLink')]
    public SaleCreatedEventLink $link;

    /**
     *
     * @var Sale $sale
     */
    #[\JMS\Serializer\Annotation\SerializedName('sale')]
    #[\JMS\Serializer\Annotation\Type('\Dub\Models\Components\Sale')]
    public Sale $sale;

    /**
     * @param  string  $eventName
     * @param  SaleCreatedEventCustomer  $customer
     * @param  SaleCreatedEventClick  $click
     * @param  SaleCreatedEventLink  $link
     * @param  Sale  $sale
     */
    public function __construct(string $eventName, SaleCreatedEventCustomer $customer, SaleCreatedEventClick $click, SaleCreatedEventLink $link, Sale $sale)
    {
        $this->eventName = $eventName;
        $this->customer = $customer;
        $this->click = $click;
        $this->link = $link;
        $this->sale = $sale;
    }
}