<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dub\Models\Components;


/** SaleCreatedEvent - Triggered when a sale is created. */
class SaleCreatedEvent
{
    /**
     *
     * @var string $id
     */
    #[\JMS\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     *
     * @var SaleCreatedEventEvent $event
     */
    #[\JMS\Serializer\Annotation\SerializedName('event')]
    #[\JMS\Serializer\Annotation\Type('\Dub\Models\Components\SaleCreatedEventEvent')]
    public SaleCreatedEventEvent $event;

    /**
     *
     * @var string $createdAt
     */
    #[\JMS\Serializer\Annotation\SerializedName('createdAt')]
    public string $createdAt;

    /**
     *
     * @var SaleCreatedEventData $data
     */
    #[\JMS\Serializer\Annotation\SerializedName('data')]
    #[\JMS\Serializer\Annotation\Type('\Dub\Models\Components\SaleCreatedEventData')]
    public SaleCreatedEventData $data;

    /**
     * @param  string  $id
     * @param  SaleCreatedEventEvent  $event
     * @param  string  $createdAt
     * @param  SaleCreatedEventData  $data
     */
    public function __construct(string $id, SaleCreatedEventEvent $event, string $createdAt, SaleCreatedEventData $data)
    {
        $this->id = $id;
        $this->event = $event;
        $this->createdAt = $createdAt;
        $this->data = $data;
    }
}