<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dub\Models\Components;


/** TargetPartner - The target partner account that the source account was merged into. */
class TargetPartner
{
    /**
     * The partner's unique ID on Dub.
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     * The partner's unique ID in your system
     *
     * @var ?string $tenantId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('tenantId')]
    public ?string $tenantId;

    /**
     * The partner's email address.
     *
     * @var ?string $email
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('email')]
    public ?string $email;

    /**
     * @param  string  $id
     * @param  ?string  $tenantId
     * @param  ?string  $email
     * @phpstan-pure
     */
    public function __construct(string $id, ?string $tenantId = null, ?string $email = null)
    {
        $this->id = $id;
        $this->tenantId = $tenantId;
        $this->email = $email;
    }
}