<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dub\Models\Components;


/** A short code indicating the error code returned. */
enum UnauthorizedCode: string
{
    case Unauthorized = 'unauthorized';
}
