name: Generate
permissions:
    checks: write
    contents: write
    pull-requests: write
    statuses: write
"on":
    workflow_dispatch:
        inputs:
            force:
                description: Force generation of SDKs
                type: boolean
                default: false
            push_code_samples_only:
                description: Force push only code samples from SDK generation
                type: boolean
                default: false
            set_version:
                description: optionally set a specific SDK version
                type: string
            target:
                description: 'optionally: set a specific target to generate, default is all'
                type: string
    schedule:
        - cron: 0 0 * * *
jobs:
    generate:
        uses: speakeasy-api/sdk-generation-action/.github/workflows/workflow-executor.yaml@v15
        with:
            force: ${{ github.event.inputs.force }}
            mode: pr
            push_code_samples_only: ${{ fromJSON(github.event.inputs.push_code_samples_only != '' && github.event.inputs.push_code_samples_only || 'false') }}
            set_version: ${{ github.event.inputs.set_version }}
            speakeasy_version: latest
            target: ${{ github.event.inputs.target }}
        secrets:
            github_access_token: ${{ secrets.GITHUB_TOKEN }}
            packagist_token: ${{ secrets.PACKAGIST_TOKEN }}
            speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}
